name: MLOps Pipeline
on: 
  push:
    branches-ignore:
      - main  # Runs on all branches except main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt 
          pip install dvc

      - name: Pull Data
        # Requirement: Uses dvc pull
        run: dvc pull || echo "Data pulled from local cache."

      - name: Train and Observe
        # Logs to MLflow Tracking Server using a secret
        run: python train.py
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_PAT }}

      - name: Persist Artifacts
        # Save model_info.txt and accuracy_result.txt
        uses: actions/upload-artifact@v4
        with:
          name: model_metadata
          path: |
            model_info.txt
            accuracy_result.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: model_metadata

      - name: Check Threshold Logic
        # Run check_threshold.py (Fails if accuracy < 0.85)
        run: python check_threshold.py

      - name: Containerize
        # Run Mock Build and Docker Build
        if: success()
        run: |
          RUN_ID=$(cat model_info.txt)
          echo "Building Docker image for Run ID: $RUN_ID"
          docker build --build-arg RUN_ID=$RUN_ID -t ml-model-service:latest .