name: MLOps Pipeline
on:
  push:
    branches-ignore:
      - main  # This tells GitHub: "Run on every push EXCEPT to the main branch"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install pandas scikit-learn numpy dvc
      - name: Train Model
        run: python train.py
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline_data
          path: "*.txt"

  deploy:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: pipeline_data
      - name: Check Threshold
        run: python check_threshold.py
      - name: Mock Build
        run: |
          RID=$(cat model_info.txt)
          echo "Building Docker image for Run ID: $RID"
          # Optional: add your docker build command here