name: ML Pipeline

on: 
  push:
    branches-ignore:
      - main 
jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc

      - name: Pull data with DVC
        run: |
          dvc pull

      - name: Train model
        run: python train.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: model_info
          path: model_info.txt

  deploy:
    needs: validate
    runs-on: ubuntu-latest

    env:
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install mlflow

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: model_info

      - name: Check accuracy threshold
        run: python check_threshold.py

      - name: Mock Docker Build
        run: |
          echo "Building Docker image for Run ID: $(cat model_info.txt)"